[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "asr"
version = "0.1.0"
requires-python = ">=3.12"

dependencies = [
    "asyncio",
    "fastapi",
    "matplotlib",
    "numpy",
    "requests",
    "soundfile",
    "sounddevice",
    "tensorboard",
    "torch",
    "torchaudio",
    "torchcodec",
    "torchinfo",
    "transformers",
    "uvicorn[standard]"
]

[tool.setuptools]
py-modules = ["vader", "transcriber", "server"]
